### ISSUE TITLE
make_point_cの作成、initializer_listではなく他の方法を

### ISSUE THREAD

**Issue by yumetodo** [Nagarei/DxLibEx#14]
# 背景

#2 より

```cpp
#include <dxlibex/basic_types.hpp>
class object_to_fall_c
{
public:
    explicit object_to_fall_c(const object_to_fall_c& o);
    object_to_fall_c(int x, int y, int pixcel_per_frame, const DxGHandle& handle);
//略
private:
    dxle::pointi self_;
    int pixcel_per_frame_;
    DxGHandle handle_;
};
object_to_fall_c::object_to_fall_c(int x, int y, int pixcel_per_frame, const DxGHandle & handle) : handle_(handle), self_({x, y}), pixcel_per_frame_(pixcel_per_frame) {}
```

のような場合、self_がどのコンストラクタか、オーバーロードの解決ができなかった。

std::pairをとるコンストラクタのせいで、曖昧になっていた

→initializer_listをとるコンストラクタを追加

→initializer_listの大きさが2より大きい時、コンパイルエラーにできない

→**これはバグ**

→``std::pair``からの変換は外部関数にしょう

**Comment by yumetodo** [comment]
コンストラクタに``explicit``がつけられないため、想定外のことが起きないか不安です

**Comment by Nagarei** [comment]
> コンストラクタに`explicit`がつけられない

とはどういう意味でしょう？

ところで見当違いかもしれませんが、
```cpp
point_c(value_type x_) DXLE_NOEXCEPT : x(x_), y() {}
point_c(value_type x_, value_type y_) DXLE_NOEXCEPT : x(x_), y(y_) {}
```
この二つのコンストラクタには`explicit`を付けるべきでしょうか？
僕は一つ目はつけたほうが良いと思います。
二つ目は
```cpp
pointi f(){
    int x, y;
    /*何か処理*/
    return {x, y};
}
```
のようなコードを許可するためにつけないほうが良いと思います。

**Comment by yumetodo** [comment]
```cpp
explicit point_c(value_type x_) DXLE_NOEXCEPT : x(x_), y() {}
```

だと

```cpp
dxle::point_c<int> p7 = 0;
dxle::point_c<float> p7_1 = 0;
```

が通らないです。

**Comment by Nagarei** [comment]
しかし、explicitがないと以下のコードが通ってしまいます。
```cpp
tx.DrawGraph(0, true);//y座標の指定を忘れた！
```

**Comment by yumetodo** [comment]
でも

```cpp
dxle::point_c<int> p7 = {};//OK
dxle::point_c<int> p7 = { 0 };//NG
dxle::point_c<int> p7 = { 0, 2 };//NG
```

```cpp
class object_to_fall_c
{
public:
	object_to_fall_c(int x, int y, int pixcel_per_frame);
private:
	dxle::pointi self_;
	int pixcel_per_frame_;
};
object_to_fall_c::object_to_fall_c(int x, int y, int pixcel_per_frame)
 : self_({ x, y }), pixcel_per_frame_(pixcel_per_frame) {}//NG
```
これは解せない気が

**Comment by Nagarei** [comment]
引数二つのコンストラクタのexplicitを外したので、これで`dxle::point_c<int> p7 = { 0, 2 };`とobject_to_fall_cの例は大丈夫です。

引数一つのコンストラクタですが、個人的には、
 座標クラスが引数一つのみを受け取ったときに、引数をxにあてて、yを0と推量する
というのは、**yを0と推量する根拠がない**ような気がするので違和感があります。

違和感がないものは例えば
分数クラスが引数一つのみを受け取ったときに、引数を分子にあてて、分母を1と推量する
という物です。これは、「一つのみの引数は整数として扱う」という論理がはっきり見えるからです。

**Comment by yumetodo** [comment]
>yを0と推量する根拠がない

例えばですね、

```cpp
int a1;
a1 = 0;
int a2();
int a3 = 0;
int a4{};
int a5{ 0 };
int a6 = {};
int a7 = { 0 };
```

この差を説明できる人が使うぶんにはいいんですけど、そうでない人が

```cpp
dxle::point_c<int> p = 0;//NG
```

を理解できるかな、って話なんですよね。まあ「仕様です」でもいいとは思いますが・・・。

**Comment by Nagarei** [comment]
前の僕のコメントは「そもそも引数一つを受け取るコンストラクタはいらないのではないか」という意味です。
わかりづらく、乱暴な意見ですみません。
そもそもなければ上の例はa2,a4,a6以外全てNGになるので、混乱も生じないです。

**Comment by yumetodo** [comment]
あ、大丈夫です。ちゃんと理解しています。ただ=0で初期化したい人はいるだろうな、と思ったので。

そこを重視しなくていいなら

>まあ「仕様です」でもいいとは思いますが・・・。

ということです。

**Comment by Nagarei** [comment]
xとyからなる座標を=0で初期化するというのは「間違い」だと思うので削除して良いでしょうか？
「仕様です」で良いと思います。

**Comment by yumetodo** [comment]
除去しました
