### ISSUE TITLE
point_cのistream operator>>のバグ

### ISSUE THREAD

**Issue by yumetodo** [Nagarei/DxLibEx#15]
例えば

```cpp
dxle::pointi in_p;
std::cin >> in_p;
```

とあったとき、

```
-2.4, 5.3
```

のように入力すると

```
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Debug Error!

Program: ...git\DxLibEx\samples\calc_coordinate\Debug\calc_coordinate.exe
Module: ...git\DxLibEx\samples\calc_coordinate\Debug\calc_coordinate.exe
File: 

Run-Time Check Failure #2 - S

(Press Retry to debug the application)

---------------------------
中止(A)   再試行(R)   無視(I)   
---------------------------
```

となる

**Comment by yumetodo** [comment]
なおg++/clang++でコンパイルして実行すると

```
3, 5 のように入力してください
-2.4, 5.3
in_p:-2, 5
```

のように正常に動いているように見える

**Comment by Nagarei** [comment]
どうやら
xに"-2"を入れた後
bufに".4, "を入れようとして範囲外アクセスになっているようです。
対処方
 - bufをstd::stringに変える
   - パフォーマンスに影響がでる
 - bufを大きくする
   - パフォーマンスに影響がでる
   - 5.11111111...のような悪質なケースに対応できない
 - 仕様にする（入力は整数のみ）
  - 悪質なケースに対応できない
 - x,yを浮動点小数型にする

どれが良いでしょうか？

**Comment by yumetodo** [comment]
多分``istream::getline``で読み込み数にlimitかけつつ、ということになると思います。

でもなんでgccとclnagは通したんだろう・・・

**Comment by Nagarei** [comment]
istream::ignoreを使えばよかったことに気が付いたので、これで修正しました。

> なんでgccとclnagは通したんだろう・・・

標準ではこのチェックは義務付けられていないからだと思います。
（VC++でも範囲外アクセスのエラーではなく、スタック破壊のエラーになっています）

**Comment by yumetodo** [comment]
>istream::ignoreを使えばよかった

その発想はなかった!!

ずっとignoreに相当するコードを自分で書くためにあーでもないこーでもない、マニピュレータがーとかやってた。

**Comment by yumetodo** [comment]
これでこの件はfixしたと思うので閉じます
