### ISSUE TITLE
max,minマクロの対応

### ISSUE THREAD

**Issue by Nagarei** [Nagarei/DxLibEx#17]
max,minマクロへの対応を協議する

参照：http://d.hatena.ne.jp/yohhoy/20120115/p1
とりあえずはここの回避策3でなんとかなるとは思います。

**Comment by yumetodo** [comment]
個人的には全ヘッダーファイルで

```cpp
#ifndef NOMINMAX
#define NOMINMAX
#endif
```

を冒頭につけるべきだと思っているんですが。

**Comment by yumetodo** [comment]
あーでも

#11 

がらみでsproutみてたら``SPROUT_PREVENT_MACRO_SUBSTITUTION``マクロ作ってるな・・・

**Comment by Nagarei** [comment]
boostの定義を見たら
```cpp
#define BOOST_PREVENT_MACRO_SUBSTITUTION
```
と、ただの空defineだったので、これは候補になると思います。
とりあえず候補を挙げてみます。
 - ユーザーに選択の余地を残すという意味で、NOMINMAXを使わない
 - min,maxマクロは悪しき習慣だからNOMINMAXを定義する
 - デフォルトでNOMINMAXを定義し、USEMINMAXが定義されたときだけ定義しない（これは良いのか？）

**Comment by yumetodo** [comment]
とりあえずsproutにならって

https://github.com/Nagarei/DxLibEx/commit/df4e8da313fe025bbff568fadafeb733db1f95ba

で

```cpp
#define DXLE_PREVENT_MACRO_SUBSTITUTION
```

を作ってありますが。

正直C++ユーザーにはmin,maxマクロは百害あって一利なしなんですよね。MSが

```cpp
#if !defined(__cplusplus) || !defined(NOMINMAX)
#ifndef max
#define max(a,b)            (((a) > (b)) ? (a) : (b))
#endif
#ifndef min
#define min(a,b)            (((a) < (b)) ? (a) : (b))
#endif
#endif  //!defined(__cplusplus) || !defined(NOMINMAX)
```

としてくれるのが一番いいんですが、そんな未来は来ないと思うので

>min,maxマクロは悪しき習慣だからNOMINMAXを定義する

に一票ですね・・・。


ちなみにsproutで``SPROUT_PREVENT_MACRO_SUBSTITUTION``マクロ使ってるのは
https://github.com/bolero-MURAKAMI/Sprout/blob/master/sprout/net/endian.hpp
これだけっぽいですね。


なので

- NOMINMAXを定義する
- DXLE_PREVENT_MACRO_SUBSTITUTIONは https://github.com/Nagarei/DxLibEx/commit/df4e8da313fe025bbff568fadafeb733db1f95ba のままdefineしておく

の並行路線を提案します

**Comment by Nagarei** [comment]
では、
- NOMINMAXを定義する
- DXLE_PREVENT_MACRO_SUBSTITUTIONは残す

の並行路線で行きましょう。

インクルード前にすでにmin.maxが定義されていた場合はどうしましょうか？
undefをかけたほうが良いですかね？

**Comment by yumetodo** [comment]
undefしつつNOMINMAXを定義するヘッダをつくりましょう。で全部のヘッダーの先頭でincludeすればいいかと

**Comment by Nagarei** [comment]
config系のヘッダーではインクルードしてないですけど、問題ないですよね？

**Comment by yumetodo** [comment]
問題ないと思います。
closeします

**Comment by yumetodo** [comment]
http://stackoverflow.com/questions/4597281/mysql-headers-conflict-with-stl-algorithm-in-c

MySQLでもあったのか、この問題・・・。
