### ISSUE TITLE
pointクラスを作る

### ISSUE THREAD

**Issue by yumetodo** [Nagarei/DxLibEx#2]
#1 で決定したので作る。

### point系
- std::pair  
http://en.cppreference.com/w/cpp/utility/pair/pair
- cv::Point_  (3-clause BSD License)  
http://docs.opencv.org/master/db/d4e/classcv_1_1Point__.html#gsc.tab=0
- cv::Size_  (3-clause BSD License)  
http://docs.opencv.org/master/d6/d50/classcv_1_1Size__.html#gsc.tab=0
- sf::Vector2  (zlib License)  
http://www.sfml-dev.org/documentation/2.0/classsf_1_1Vector2.php
- sprout::pair  (Boost Software License - Version 1.0)  
https://github.com/bolero-MURAKAMI/Sprout/blob/master/sprout/utility/pair/pair.hpp
- QPoint  (GNU Lesser General Public License)  
http://doc.qt.io/qt-5/qpoint.html

### C++規格系
- C++の規格におけるcontextually converted to boolという用語について | 本の虫  
http://cpplover.blogspot.jp/2015/09/ccontextually-converted-to-bool.html
-  C++0x explicit bool - Faith and Brave - C++で遊ぼう  
http://faithandbrave.hateblo.jp/entry/20081222/1229936810
- C++ - std::enable_ifを使ってオーバーロードする時、enablerを使う？ - Qiita  
http://qiita.com/kazatsuyu/items/203584ef4cb8b9e52462

**Comment by yumetodo** [comment]
とりあえず整数型に限定していいだろうということでSFINAEで弾いています。

[sproutのpairの実装](https://github.com/bolero-MURAKAMI/Sprout/blob/master/sprout/utility/pair/pair.hpp)とか[std:pair](http://ja.cppreference.com/w/cpp/utility/pair/pair)みるとtupleを受け取るconstructorがあるけど、これはどうやってつかうんだろう・・・

**Comment by Nagarei** [comment]
DXライブラリには実数型(float)を引数にとる関数もあるので、実数版も作ったほうが良いと思います。(DrawGraphFなど)
別クラスにするかTの制限を算術型に緩和するかですね。
とりあえずnoexceptが2013でコンパイルできないとかSFINAEのミスとかを修正した物をpull requestしておきます。

あと、僕の使っているC++のサイトを紹介しますね。
- cpprefjp - C++日本語リファレンス  
http://cpprefjp.github.io/reference.html

**Comment by yumetodo** [comment]
>実数版も作ったほうが良いと思います

表記ミスです、算術型に限定しています。

>SFINAEのミス

あ、``typename``書き漏らしてましたね。
http://qiita.com/kazatsuyu/items/203584ef4cb8b9e52462
を参考に書いています。``std::nullptr_t``が使われているのはそのためです。

cpprefjpにはいつもお世話になっています。

・・・というかbranchを分けて作業しようと思っていたのに忘れていました。

**Comment by Nagarei** [comment]
tupleを受け取るコンストラクタは以下のようにクラスをコピーでなく直接構築したい場合に使うようです。
(参考 http://cpprefjp.github.io/reference/utility/pair/op_constructor.html)
```
#include <utility>
#include <tuple>
struct X {
  int a, b, c;
  X(const X&) = delete;
  X(int a, int b, int c) : a(a), b(b), c(c) {}
};
struct Y {
  int a, b;
  Y(const Y&) = delete;
  Y(int a, int b) : a(a), b(b) {}
};
// (8) first_typeとsecond_typeのコンストラクタ引数を受け取って構築
int main()
{
    //OK
    std::pair<X, Y> p8(std::piecewise_construct,
                       std::make_tuple(1, 2, 3),
                       std::make_tuple(4, 5));
    //エラー
    //std::pair<X, Y> p8(X(1, 2, 3), Y(4, 5));
}
```
これも追加したほうが良いかもしれませんね。

**Comment by yumetodo** [comment]
算術型以外で座標クラスを使うとは考えにくく、その場合はそれこそ``std::pair``なりを使えばいい気がするんですが、必要ですかね・・・？

**Comment by Nagarei** [comment]
> std::nullptr_t

なるほど。そういう理由でしたか。nullptr_tの方に戻しておいてください。
> 算術型以外で座標クラスを使うとは考えにくく

よくよく考えたらそうでした...。まあ僕は分数クラスを作ったことがあるので「考えられなくはない」ですが...。これは後回しで良いですね。

**Comment by yumetodo** [comment]
>分数クラスを作ったことがあるので

その発想はなかったですが、それは後回しで。

**Comment by Nagarei** [comment]
何個か質問させてください。
- 9行目:デフォルト引数` = nullptr`が抜けてます。
- 15行目:0との比較とは(0,0)との比較のことですか？
- 19,21行目:explicitなのはなぜですか？
- 30行目:trueとなるのは(0,0)でないときという認識で良いですか？
- 32行目:namespaceを閉じるのが早いです。operatorもnamespaceの中に入れておいてください。
- 59,75,143,172行目:`operator +=`ってメンバ関数じゃないといけなかった気がします。（僕の勘違いだったら無視してください）

**Comment by yumetodo** [comment]
>15行目:0との比較とは(0,0)との比較のことですか？

```cpp
auto p = point_c(0, 0);
bool con = (0 == p);//true
```

はい。

>19,21行目:explicitなのはなぜですか？

どこかでとりあえあず``explicit``つけとけ、と書いてあったので。とくに支障はないと思いますが・・・。

>30行目:trueとなるのは(0,0)でないときという認識で良いですか？

はい

>32行目:namespaceを閉じるのが早いです。operatorもnamespaceの中に入れておいてください。

operatorが見つからないと思っていましたが、考えてみたら悪名高いArgument Dependent Lookupがあるのでそんなことはないですね。

>``operator +=``ってメンバ関数じゃないといけなかった気がします。

その部分はとりあえずということでSFMLのVector2 classの実装をコピペしたんですが、(license的にはBSDだから問題ないはず)、そういえばクラス外に自身への和差積商のoperatorを書くのを見るのは初めてですね・・・。STLとかQPointはクラス内に定義してますし。

**Comment by yumetodo** [comment]
なぜか

```cpp
point_c(std::nullptr_t) noexcept;
```

の定義だけだと

```cpp
auto p = point_c(0, 0);
bool con = (0 == p);//true
```

が通らなかったのでやむなく``operator==``を書きました。

結局copy/move constructorがexplicitだとconstructorを見つけられないようで、また``sprout::pair``の実装でも``explicit``はついてなかったので、外すことにしました。

sampleのコンパイルエラー見る限り、``std::forword``の使い方を間違っているようです・・・何が違うんだ。

**Comment by Nagarei** [comment]
> std::forwordの使い方を間違っているようです

この場合はstd::moveを使ってください。
```
//std::forwardの使い方（蛇足）
template<typename T>
void f(T&& v){
	other_func(std::forward<T>(v));
}
```
 - convert constructorについて

explicitを付けたほうが良いと思います。あと、型変換が可能な全てのpairを引数にとれるようにもできますがやりますか？

 - 単項operator-について

単項operator-があったので、一応単項operator+を追加しておきます

**Comment by Nagarei** [comment]
> あと、型変換が可能な全てのpairを引数にとれるようにもできますがやりますか？

現状のままでできました。std::pairの方がこれをできるので、`std::pair<value_type, value_type>&&`の方のコンストラクタに引っかかったようです。

**Comment by yumetodo** [comment]
move周りの修正ありがとうございます。

point_cの特殊化のtypedefを追加しました。

```cpp
	typedef point_c<int> pointi;
	typedef point_c<uint8_t> pointu8i;
	typedef point_c<int8_t> point8i;
	typedef point_c<double> pointd;
	typedef point_c<float> pointf;
```

またstd::ostreamのoperator<<を作成しましたが、自信がないです・・・。

**Comment by Nagarei** [comment]
Pull requestが出ていますが、無視してください。
出した後で変更が完全に無意味だったことに気が付きました...。

**Comment by Nagarei** [comment]
Pull requestのコードにwchar_tとか、char16_tとかが書いてありますが、僕の思い込みです...。出した後に気が付きました...。元のoperator<<でも十分ですね...。
何らかの形でoperator>>が実装されていれば僕のPull requestは無視してもらって構いません。

**Comment by yumetodo** [comment]
そもそも``operator>>``が必要になるシーンがわからないんですが・・・。そもそも何を区切り文字にしますか？(Pull Requestのは強制的に2byte切り捨ててますが)

**Comment by Nagarei** [comment]
operator<<があるならそれに対応するoperator>>も必要だと思います。
区切り文字はとりあえずoperator<<に合わせた結果ああなっています。

**Comment by yumetodo** [comment]
#5 を修正しつつmargeしたので、あとはコメントをちゃんと書かないといけませんね・・・。

**Comment by Nagarei** [comment]
```
\~english	comment
\~japanese	コメント
	@code
	    ...
```
となっていましたがこれだと`@code`の部分が日本語専用の記述として認識されてしまうようです
とりあえず`\~japanese`と`@code`の間に`\~`を入れることで解決しました。
そしてまたコミットとissueの関連付けを忘れた...。

**Comment by yumetodo** [comment]
あー、時間がなくてテストしなかったらこの有り様だ・・・。修正ありがとうございます。

>そしてまたコミットとissueの関連付けを忘れた...。

まれによくあります。

```sh
git commit --amend -m "あたらしいメッセージ"
```

で直前のメッセージを変えられるんですが、pushするときに-fをつけないで失敗してmaegeする羽目になったのが
https://github.com/Nagarei/DxLibEx/commit/17c7d4470e9c772017b5bea0bb797e6d9f3bafea
これでして・・・・

**Comment by yumetodo** [comment]
いざ
https://github.com/TakeObara/DoNotPushGame
で使ってみようとしたら結構いろいろエラーが出たので直しました。

まさかoperator類の定義を綺麗さっぱり忘れてたとは・・・。

initializer_listをとるコンストラクタを追加しました。これは

```cpp
#include <dxlibex/basic_types.hpp>
class object_to_fall_c
{
public:
	explicit object_to_fall_c(const object_to_fall_c& o);
	object_to_fall_c(int x, int y, int pixcel_per_frame, const DxGHandle& handle);
	object_to_fall_c(const dxle::pointi& p, int pixcel_per_frame, const DxGHandle& handle);
	dxle::pointi xy_move();
	bool collision_detecter(int target_x, int target_y, const DxGHandle& target_handle);
	bool collision_detecter(const dxle::pointi&  target, const DxGHandle& target_handle);
private:
	dxle::pointi self_;
	int pixcel_per_frame_;
	DxGHandle handle_;
};
object_to_fall_c::object_to_fall_c(int x, int y, int pixcel_per_frame, const DxGHandle & handle) : handle_(handle), self_({x, y}), pixcel_per_frame_(pixcel_per_frame) {}
```

のような場合、self_がどのコンストラクタか、オーバーロードの解決ができなかったためです。std::pairをとるコンストラクタのせいで、曖昧になっていたようです。

が、現在の実装は問題があって

```cpp
DXLE_CONSTEXPR point_c(std::initializer_list<T> values) DXLE_NOEXCEPT : x((values.size()) ? *values.begin() : 0), y((0 < values.size()) ? *(values.begin() + 1) : 0) {}
```

``initializer_list``の大きさが2より大きい時、コンパイルエラーになりません。
http://qiita.com/kktk-KO/items/64b693c84ca0ee4ecbe0
これみて実装しようかと思ったんですが、さっぱりわからず、お手上げです。

**Comment by Nagarei** [comment]
URLのやつがこのケースの場合使えないという事だけはわかりました。
可変長引数テンプレートを使ったコンストラクタはオーバーロード解決の優先順位が最も下になるので、
どうやってもより優先順位が高い二つのオーバーロードが競合しているこのケースの解決策にはなりません。

あり得る解決策としては「std::pairとの互換をなくす」ですが...。

**Comment by yumetodo** [comment]
initializer_listをとるコンストラクタの中でstatic_assertとかも考えたんですが、だめですね。

std::pairからの変換は別途``make_point_c``とかつくってそれでやったほうがいいですかね・・・。

さすがにこれを「仕様です」と逃げるのはまずいです・・・よね？

**Comment by Nagarei** [comment]
> 別途make_point_cとかつくって

それが良いと思います。さすがにこれを仕様にはできないので...。

**Comment by yumetodo** [comment]
ええっとそこはかとなくabs関数を追加したんですが、これは

[C++で常微分方程式：boost::odeint入門 | Qiita](http://qiita.com/hmito/items/483445ac0d42fb4428a5#%EF%BC%92%E3%83%9D%E3%82%A4%E3%83%B3%E3%83%88%E3%82%BF%E3%82%A4%E3%83%97%E3%81%AEstate%E3%81%AE%E8%87%AA%E4%BD%9C)

を見て、この要件(リンク先　付録1ポイントタイプのstateの自作を参照)を満たすくらいならすぐできるんじゃないか？とおもって追加したものです(私はboost::odeintを使うつもりはないが、そのライブラリ的に親和性は高そうだったから追加して損はないと思った)。ただほかにも

- stateの要素ごとの除算``state_type operator/(state_type)``が可能
- stateの要素の絶対値の最大値を求めるクラス、``boost::numeric::odeint::vector_space_norm_inf<T>``を特殊化している。 

という要件があって、これはいきなりは追加できないな、と思い追加していません。

とくに

>要素ごとの除算

という部分なんですが、これはつまり統一性の観点から、四則演算すべて対応する必要が出てきて、掛け算の場合、内積・外積と紛らわしい、という問題があります。(そういえば実装していませんが、OpenCVのcv::Point_には内積と外積を計算するメンバー関数がある)

追加しましょうか？

要件2つめに関して実装するとしたら例えば``DXLE_ENABLE_BOOST_ODEINT``マクロが定義されたときのみ、となると思いますが。

**Comment by Nagarei** [comment]
23日も放置してしまった...。申し訳ないです。

point_cが何者なのかという問題になると思います。
ベクトルだとすると
 - 加算減算は実装したい
 - 内積外積を計算するメンバー関数も実装したい
 - 大きさを求める関数も欲しい
 - 除算は定義されていないのでないほうが良い

となると思います。
単純に座標だとすると中の二つもないほうが良いという事になりますが、よく使うのであったほうが良いでしょう。
たぶんこれが一般的な使われ方です。

一方boost::odeintに対応するとなると最早ベクトルではないですよね？同じクラスに二つの意味があることになり、混乱を招くので避けたほうが良いかと思います。
defineで切り替えるにしろ、有効な状態では同じことです。

**Comment by yumetodo** [comment]
書いた本人が忘れてました。

これはまずベクトルなんですかね・・・。するとベクトルの大きさって絶対値だよなぁ・・・。すると現状のabsは・・・

内積外積はメンバー関数よりフリー関数のほうがいいのかな。

**Comment by Nagarei** [comment]
ちょっと他のライブラリを調べてみました。
他のライブラリには無いけれどやっぱり外積もあったほうがいいような...。
XNAは座標とベクトルをはっきり分けてます。
どうするのが良いんだろうか？

| ライブラリ    | 内積       | 外積       | abs        | 大きさ     |
|---------------|------------|------------|------------|------------|
| OpenCV        | メンバ関数 | なし       | なし       | 外部関数   |
| Java          | なし       | なし       | なし       | 二点間の距離を求める外部関数とメンバ関数   |
| XNA(Point)    | なし       | なし       | なし       | なし       |
| XNA(Vector2D) | メンバ関数 | なし       | なし       | メンバ関数 |

**Comment by yumetodo** [comment]
とりあえずメンバー関数が肥大化するのもどうかと思うのでフリー関数にするとして、内積、外積をつくり、大きさはdistanceでいいや、という風に思っています。(2次元で外積って意味あるの？てか何時使うんだ)

**Comment by Nagarei** [comment]
その方針で良いと思います。abs関数も削除の方が良いですかね？

2Dの外積は当たり判定でよく使います。点が直線のどちら側にあるのかが判定できるので。

**Comment by yumetodo** [comment]
absは・・・あったらあったで使うだろう。ただし今の実装だとfloat, double, long doubleにしか使えない気がするから実装は変えないと・・・。

**Comment by Nagarei** [comment]
外積はcrossで良いと思います。
absの問題は混乱を招くかどうかですよね...。実際に試さないとユーザーの反応が分からないのが辛いです。
constexpr_if作ってみました。使い勝手はわかりませんが...。どうでしょう？
```cpp

template<bool condition, typename Func1, typename Func2>
struct constexpr_if_impl {
	static void do_work(Func1&& f, Func2&&) {
		std::forward<Func1>(f)();
	}
};
template<typename Func1, typename Func2>
struct constexpr_if_impl< false, Func1, Func2> {
	static void do_work(Func1&&, Func2&& f) {
		std::forward<Func2>(f)();
	}
};
template<bool condition, typename Func1, typename Func2>
void constexpr_if(Func1&& f1, Func2&& f2)
{

	constexpr_if_impl<condition, Func1, Func2>::do_work(std::forward<Func1>(f1), std::forward<Func2>(f2));
}
//サンプル
int main()
{
	constexpr_if<false>([] {
		std::cout << "error" << std::endl; 
	}, [] {
		std::cout << "ok" << std::endl; 
	});
	constexpr_if<true >([] {
		std::cout << "ok" << std::endl; 
	}, [] {
		std::cout << "error" << std::endl;
	});
	return 0;
}
```

**Comment by Nagarei** [comment]
> constexpr_if

あ。どっちにしろ両方評価されるから意味がないのか...。やっぱりコンパイラマジック使わないと無理かな？

**Comment by yumetodo** [comment]
C++標準に、``detail::safe_dist``みたいな関数あったと思うんだけど、見つからない・・・。

**Comment by yumetodo** [comment]
ひとまず二次元の座標クラスとしての実装は終わったかな、と思っているのですが、どうでしょうか。

**Comment by Nagarei** [comment]
一通りは終わったと考えて問題ないと思います。

**Comment by yumetodo** [comment]
@Nagarei 
ではcloseお願いします。
