### ISSUE TITLE
doxygenがらみ

### ISSUE THREAD

**Issue by yumetodo** [Nagarei/DxLibEx#27]
@Nagarei 
今``gh-pages``に上がってる最新commitが私のPCの名前が入っているみたいなので、消したいんですが、
force pushを一時的に許可してもらえませんか？
GitHubのSettingからできるはずなので。
![image](https://cloud.githubusercontent.com/assets/10869046/12163491/66ca9ad2-b551-11e5-9328-608663531e0f.png)

**Comment by Nagarei** [comment]
@yumetodo 
protectを外しておきました。

**Comment by yumetodo** [comment]
@Nagarei force pushしました。またprotectしておいてください。
