### ISSUE TITLE
type_traitsについて

### ISSUE THREAD

**Issue by Nagarei** [Nagarei/DxLibEx#28]
ある程度の数がありそうだったのでいったんまとめる。

- namespaceに入れるべきか
  - 入れるとしたらtype_traits名前空間
- 命名規則はどうするか
  - STLに従うで良いと思う
  - _t系は必ず入れる

**Comment by yumetodo** [comment]
>namespaceに入れるべきか 

spoutでも入れてないしべつにいいかなと

>命名規則はどうするか 

STLに従うで良いと思います。

それより、``type_traits``フォルダの外に``type_traits.hpp``を追加しますか？

**Comment by Nagarei** [comment]
ではnamespaceはなしで。
type_traits.hppはあったほうが良いと思います。

**Comment by yumetodo** [comment]
げ、copyright書き忘れてた。ありがとうございます。

**Comment by Nagarei** [comment]
namespaceの議論をもう一度...。（往生際が悪くて申し訳ないです）
inline namespaceなら、namespaceでの分類とコードの短さを両立できるのではないでしょうか？
（VC2013が対応していないので、dxle内でusing namespaceをすることでの実装になりますが）
doxygenでの分類もできるようになります。

**Comment by yumetodo** [comment]
それ、ADLで問題になりませんかね・・・。私はむしろそのほうがいいんですけど、関数がnamespace省略できなくなったりとかとか・・・

**Comment by Nagarei** [comment]
少し考えたのですが、doxygenでの分類ができるようになるというほうを優先したほうが良いという結論に達しました。
inline namespaceが使えるなら良いんですけどね...。
> 関数がnamespace省略できなくなったり

結局本家DxLibの方に、DX_NON_USING_NAMESPACE_DXLIBを追加していただいたので、一応省略できます。サンプルなどに書いて宣伝すれば大丈夫でしょう。

...DxLibの関数のラップ最近作ってないな...。

**Comment by yumetodo** [comment]
>結局本家DxLibの方に、DX_NON_USING_NAMESPACE_DXLIBを追加していただいたので、一応省略できます。

その話は掲示板で見てましたが、

```cpp
using namespace DxLib;
```

を無効にするマクロですよね？その話がどう関係するんでしょう。

**Comment by Nagarei** [comment]
`using namespace DxLib;`が無効になっていれば`using namespace dxle;`を使っても競合しなくなるので、ADLでない方向で省略できるので、大丈夫かなと。

**Comment by yumetodo** [comment]
あ、そういうことか。なるほど。

**Comment by yumetodo** [comment]
@Nagarei 
多分終わっているのでcloseお願いします
