### ISSUE TITLE
Gitサーバーの分散

### ISSUE THREAD

**Issue by yumetodo** [Nagarei/DxLibEx#39]
今回みたいにGitHubが落ちて何もできない状態があると不味いので、SourceTreeから利用しやすいbitbucketにもリポジトリを置くことを提案します。

私個人のリポジトリはすでに幾つかコピーしましたが

>ex.)
>https://github.com/TakeObara/DoNotPushGame
>https://bitbucket.org/yumetodo/donotpushgame

弊害はSource Tree でcommitと同時には複数のremoteにpushできない程度で問題なく使えています

なおGitHub pagesのように、Bitbucket Pagesもあるようですが、
http://www.techrepublic.com/article/host-static-websites-for-free-with-bitbuckets-git-feature/
さすがにそこまでしなくていいかなと思っています。

**Comment by Nagarei** [comment]
Bitbucketについて詳しくないのですが、5人までのプロジェクトなら無料という事は6人以上になると問題になるのではないでしょうか？
まあ、現状そんなにいませんが...。

**Comment by yumetodo** [comment]
>5人までのプロジェクトなら無料

それはGitHubでいう組織アカウントを作る時の話だったと思います。
各リポジトリに参加できる人数とは関係無かったと思います。

実験ということで私が管理人役になってむこうに上げてNagarei さんを招待しますか？(もちろんNagarei さんもアカウントを持たないとダメです)

**Comment by Nagarei** [comment]
やっとBitbucketのアカウントが作れました...。
勝手が分からないので、招待してください。

**Comment by yumetodo** [comment]
えっとこれで合っていますかね？アカウント
https://bitbucket.org/Nagarei/

**Comment by Nagarei** [comment]
それです。

**Comment by yumetodo** [comment]
作りました
https://bitbucket.org/yumetodo/dxlibex

**Comment by Nagarei** [comment]
ありがとうございます。ここはcloseして良いですかね？

**Comment by yumetodo** [comment]
いいと思ったのでcloseします

**Comment by yumetodo** [comment]
そういえば
https://bitbucket.org/yumetodo/dxlibex/wiki/Home

wikiもコピーしました
