### ISSUE TITLE
リファレンスにdead pageが存在する

### ISSUE THREAD

**Issue by yumetodo** [Nagarei/DxLibEx#49]
http://nagarei.github.io/DxLibEx/ja/html/a00025_source.html
のようなページ。
こういうページは検索エンジンのクローラーで収拾されることがあり、放置するのは良くない。

どういう条件でできるかわからないが、

- ファイル数、ファイル名に変更があった時はこれを防止するために一度``ja``と``en``フォルダを削除してから生成しpushすること
- 削除用のバッチファイルをmasterに追加する
- ドキュメント生成手順をWikiに記載すること

を提案する

**Comment by Nagarei** [comment]
make_html.batを削除と生成を同時に行うように変更してみましたが、どうでしょうか？
生成の最適化はできないですが、どちらにせよあまり時間はかからないので僕はこれで良いと思います。

**Comment by yumetodo** [comment]
いや、分けたほうがいいと思うんです
localで実験するのにキャッシュが効かないと面倒なので。
地味に相関図の生成に時間かかりますし

(まともな端末があるLinuxならmakefile書くんですが)

**Comment by Nagarei** [comment]
こんな感じでしょうか？

**Comment by yumetodo** [comment]
ありがとうございます。
closeします
