### ISSUE TITLE
DxLibのinclude pathには環境変数を使うべきではないか

### ISSUE THREAD

**Issue by yumetodo** [Nagarei/DxLibEx#55]
サンプルやテストケースではDxLibのinclude pathやlib pathの設定に環境変数を用いるべきではないか。

具体的には``DXLIB_ROOT``という環境変数を参照する。

例えばこの変数には``D:\lib\DxLib_VC\プロジェクトに追加すべきファイル_VC用``などが設定される

**Comment by Nagarei** [comment]
完全に`DXLIB_ROOT`に一本化する形で作業して良いでしょうか？

**Comment by yumetodo** [comment]
はい。

**Comment by soukouki** [comment]
#61 で漏れを対処しておきました
READMEなどで明記しておいたほうが良いのでは？

**Comment by Nagarei** [comment]
[wikiに](https://github.com/Nagarei/DxLibEx/wiki/for-AUTHORS)開発者向けのページを作りました。やっつけですが...。
READMEにも誘導を付けておきます。

**Comment by soukouki** [comment]
wikiのファイル名を変更したので #64 ができました

**Comment by soukouki** [comment]
変更漏れ多いですね・・・
