### ISSUE TITLE
アニメーションを管理するutilityの作成

### ISSUE THREAD

**Issue by Nagarei** [Nagarei/DxLibEx#56]
アニメーションする画像を一つの画像とみなすラッパークラスの提案

仮実装:  8437349
問題点

- const関数内で画像を切り替えるのは良いのか
- 名前はこれで良いのか。長すぎないか。一般的すぎないか。(特にtime系)

改善点
- デフォルトコンストラクタと、コンストラクト後に設定する関数の実装

使用イメージ（仮実装での使用方法)
```cpp
//実行結果はDxLibのLoadDivGraphサンプルと同じ(に見える)

int WINAPI WinMain(HINSTANCE, HINSTANCE,LPSTR, int)
{
	ChangeWindowMode(TRUE);
	if (DxLib_Init() == -1)        // ＤＸライブラリ初期化処理
	{
		return -1;        // エラーが起きたら直ちに終了
	}
	SetDrawScreen(DX_SCREEN_BACK);

	using cps = dxle::time::timing_maker::count_per_second;
	using counter = dxle::time::counter;
	dxle::animation_graph graph(counter{ cps{ 10 } }, dxle::LoadDivGraph("test2.bmp", 10, { 4, 3 }, { 48, 56 }));
	graph.start();

	while (ProcessMessage() == 0)
	{
		// グラフィックの描画(自動的にアニメーションされる)
		graph.DrawGraph(0, 0, FALSE);

		ScreenFlip();
		ClearDrawScreen();
	}

	DxLib_End();            // ＤＸライブラリ使用の終了処理

	return 0;            // ソフトの終了
}
```

**Comment by yumetodo** [comment]
アニメーション、イテレータみたいなインターフェースのほうがいいかもしれない。
単項演算子++に細工してやれば実現できる気がする。

```cpp
using dxle::literals;
auto images = dxle::LoadDivGraph("test2.bmp", 10, { 4, 3 }, { 48, 56 })
dxle::animation_graph animation(images, 10_cps, dxle::animation_mode::loop)
for(auto& a : animation){
if(dxle::key_modified()) a.stop();
}
```

みたいな。(キー管理クラスないからでっち上げましたが)

**Comment by Nagarei** [comment]
```cpp
for(auto& a : animation){
if(dxle::key_modified()) a.stop();
}
```
この部分が良く分からないです。`animation`がコンテナという事はわかりましたが、`a.stop()`は何をstopしていますか。`dxle::animation_graph::value_type`は何ですか。
あと、DxLibのLoadDivGraphサンプルと同じ動作をするようなサンプルをyumetodoさんのイメージで書いていただけないでしょうか？

**Comment by yumetodo** [comment]
```cpp
int WINAPI WinMain( HINSTANCE, HINSTANCE, LPSTR, int)
{
    if( DxLib_Init() == -1 ) return -1;

    using dxle::literals;
    auto images = dxle::LoadDivGraph("test2.bmp", 10, { 4, 3 }, { 48, 56 });
    dxle::animation_graph animation(images, 10_cps, dxle::animation_mode::loop);
    //animation.start()//必要ない
    for(auto& a : animation){
        if(CheckHitKeyAll()) a.stop();
        a.DrawGraph({}, false);
    }
    DxLib_End();
    return 0;
}
```

実装のイメージとしては
http://pastebin.com/y4xBwaKg
こんな感じ？このままでは動かないけど

**Comment by Nagarei** [comment]
ごめんなさい。まだanimation_graph::iteratorが良く分からないです。
いくつか質問させてください。
1. `animation_graph`はコンテナですか。
2. `auto iter1 = animation.begin();auto iter2 = animation.begin();`と初期化したとき、
  `(++iter1) == iter2`はtrueですか。falseですか。
3. 2と同じ初期化をしたとき`*(++iter1)`と`*iter2`は同じですか。違いますか。
4. `auto iter3 = animation.begin();auto iter4 = animation.end();`と初期化したとき、
 `iter3 == iter4`にするためにはiter3にどのような操作をすれば良いですか。

**Comment by yumetodo** [comment]
1. はい
2. 上の実装だとtrueですね。ただstopを呼ばないと無限ループするのと、dxle::animation_mode::loopではないモード(dxle::animation_mode::no_loopとか)の実装が困るのでfalseにするべきかと思います。内部にsize_t型でなんかフラグを持っておくべきかなぁ
3. その予定です
4. 現状では

```cpp
(*iter3).stop()
bool con = iter3 == iter4;//true
```

**Comment by yumetodo** [comment]
方針として要素にはstart()時点の時刻を持っていてそこから起算して表示する絵を決めるという感じです
イテレータはちょっと悩んでいて
1. 同じ``animation_graph``から出来たイテレータはすべて同じにする(同時に別々の動き方をする同時再生は出来ない)
2. 毎回イテレータを生成し同時再生を認める(現状)

かな、と。

固定回ループを実現させるにはイテレータに終了情報を持たせるよりは要素に終了条件を記載したほうがいいよなぁ・・・。

**Comment by Nagarei** [comment]
なんとなくyumetodoさんのやりたいことが分かりました。
画像のコンテナからアニメーション付き画像を生成するという事ですよね？
が、イテレータという概念をここに当てはめるのはまずいと思います。
イテレータとは、配列やそれに類似するデータ構造の各要素に対する繰返し処理の抽象化である(wikipedia)ので、インクリメントされたら「**次の**」「**要素**」を指すべきです。そうでないと恐らく混乱を招きます。

よく考えると、僕の仮実装だとanimation_graphよりもcounterとderivative_texture2dを組み合わせて使う方が同時再生もできる分使いやすそうですね...。同時再生機能はつける必要がありそうです。

**Comment by yumetodo** [comment]
まあイテレータとはちょっとちがうなというのは書いてて思ったのでまあいいや。

```cpp
dxle::animation_graph graph(counter{ cps{ 10 } }, dxle::LoadDivGraph("test2.bmp", 10, { 4, 3 }, { 48, 56 }));
```

``counter{ cps{ 10 } }``って言う部分、仮実装見ても何やってるかさっぱりなんですが。少なくとも``cps``じゃなくて``count_per_second``ですよね。

なぜ
```cpp
dxle::animation_graph graph(cps{ 10 }, dxle::LoadDivGraph("test2.bmp", 10, { 4, 3 }, { 48, 56 }));
```

と書けないのか教えて下さい

**Comment by Nagarei** [comment]
> count_per_secondではなくてcpsな理由

count_per_secondだと長いと思ったのでusingしました。
> `counter{}`がある理由

本当は無くても大丈夫なようにしたいです。が、仮実装では
```cpp
template<typename timing_maker_T, enable_if_t<std::is_base_of<timing_maker::timing_maker_bace, typename std::remove_reference<timing_maker_T>::type>::value, nullptr_t> = nullptr>
explicit counter(timing_maker_T&& timing_maker);
```
このコンストラクタがexplicitになっているためできないです。これがexplicitなのはVＳ2013でつけないと
なぜかコピーコンストラクタを隠ぺいしたので、とりあえずです。

> counterのコンストラクタの引数が、count_per_secondではなくて(意味的に)timing_maker&な理由

500ms間画像1=>1000ms間画像2=>750ms間画像3
みたいなアニメーションもできるようにしたかったからです。
仮実装でこれをやると`raw_timing {{ 500ms, 1000ms, 750ms }}`になります。

**Comment by yumetodo** [comment]
>count_per_secondだと長いと思ったのでusingしました。

あ・・・・見落としてた・・・

>500ms間画像1=>1000ms間画像2=>750ms間画像3
みたいなアニメーションもできるようにしたかったからです。

あーそういう。まあただ等間隔の時が冗長だからなんとかしたい・・・

**Comment by Nagarei** [comment]
35fda32

変更点
- counterのコンストラクタのexplictを外す
- textureをvectorとして持つのではなく、ゲッターを持つように(サンプル参照)
- animation_graphのcounterの状態をデフォルトでstartに

サンプル
```cpp
int WINAPI WinMain(HINSTANCE, HINSTANCE, LPSTR, int)
{
	ChangeWindowMode(TRUE);
	if (DxLib_Init() == -1)        // ＤＸライブラリ初期化処理
	{
		return -1;        // エラーが起きたら直ちに終了
	}
	SetDrawScreen(DX_SCREEN_BACK);

	auto graphs = dxle::LoadDivGraph("test2.bmp", 10, { 4, 3 }, { 48, 56 });
	using cps = dxle::time::timing_maker::count_per_second;
	using counter = dxle::time::counter;
	dxle::animation_graph graph(cps{ 10 }, [&graphs](size_t index)->dxle::texture2d&{ return graphs[index % graphs.size()]; });
	//graph.start();
	while (ProcessMessage() == 0)
	{
		// グラフィックの描画(自動的にアニメーションされる)
		graph.DrawGraph(0, 0, false);

		ScreenFlip();
		ClearDrawScreen();
	}

	DxLib_End();            // ＤＸライブラリ使用の終了処理

	return 0;            // ソフトの終了
}
```

ユーザー定義リテラルは未実装です。
animation_graphが生成された時点でアニメーションを開始します。しかし、この設計はありなのだろうか。少なくとも` % graphs.size()`を忘れると簡単に範囲外アクセスになるのだけは避けたいですが...。

**Comment by yumetodo** [comment]
そのlambda式やだなぁ・・・。
コンテナをreference wrapperで持つとか・・・

**Comment by Nagarei** [comment]
80680ba で
```cpp
dxle::animation_graph graph1(cps{ 10 }, dxle::LoadDivGraph("test2.bmp", 10, { 4, 3 }, { 48, 56 }));
dxle::animation_graph graph2(cps{ 10 }, std::ref(div_graphs));
```
などの形式の初期化をできるようにしました。
未実装
- ユーザー定義リテラル
- 生の配列のreference wrapperを引数にとるコンストラクタ

良さそうならこのまま実装しようと思います。

**Comment by yumetodo** [comment]
>生の配列のreference wrapperを引数にとる

そんなことできるのか。生配列はポインタで持っていればいいやと思っていたので。

それでいいと思います

**Comment by Nagarei** [comment]
> 生の配列のreference wrapper

VS2013でエラーを出されたので、一応ポインタ、スマートポインタとサイズをとるオーバーロードも追加してみます。

**Comment by yumetodo** [comment]
配列への参照を受けるmake関数でも作ります？reference wrapperがmoveできたか覚えていませんが

**Comment by Nagarei** [comment]
> 配列への参照を受けるmake関数

配列への参照を許可していないのは`std::array`の動作と合わせる為にあえてですが、許可したほうが良いですかね？

とりあえず、make関数を通せばVS2013でも生の配列のreference wrapperが通るように細工をできると思うのでそれもやってみます。

**Comment by Nagarei** [comment]
残る問題は
1. const関数内で画像を切り替えるのは良いのか
2. 名前はこれで良いのか。長すぎないか。一般的すぎないか。(特にtime系)
3. make関数を作るか否か
といったところですかね。

僕は
1. ありだと思っています。
2. timerとかnamespace timeとかは一般的なので、名前の衝突が起こりそう。dxle_time.hは`dxle_`が無駄だけど、time.hにするのも怖いです。
3. 88675c2 でanimation_graphが配列を受け取れるようにしたので、make関数はいらないと判断しています。
といった感じです。

**Comment by yumetodo** [comment]
>std::refの段階でエラーなのでできない。

なんじゃそれ・・・・。本当にVS2013のサポート切りたくなってきた(まだ早い)

>timerとかnamespace timeとかは一般的なので、名前の衝突が起こりそう。

using namespaceするプログラマの自己責任。

>dxle_time.hはdxle_が無駄だけど、time.hにするのも怖いです。

原則.hppにしません？つまりtime.hpp。どうせ``dxlibex/``が前につくんだから衝突は気にする理由がわからないです。

>make関数はいらないと判断しています。

なくて実装できたならいらないと思います。
