### ISSUE TITLE
range-based forで固定回ループするためのヘルパークラスは必要か

### ISSUE THREAD

**Issue by yumetodo** [Nagarei/DxLibEx#58]
現状だと
https://github.com/Nagarei/DxLibEx/blob/e376d63f677ca995ecbdc3071748c09a02232171/tests/UnitTest/basic_types_2d.hpp#L24
くらいしか使い道無いですが

```cpp
for(auto i : rep(1000)){
    //do something
}
for(auto i : rep(2, 150)){
    //do something
}
```

みたいに書けるものを導入してはどうか。

というのも別プロジェクトで
https://github.com/YSRKEN/Shioi/blob/ee1310ef9c08c0c140e1629919e1871c41d52e11/I401/constant_range_loop.hpp
作ったので、内部実装に使いそうなら移植しようかと思ったのです。

**Comment by Nagarei** [comment]
反対する理由はないです。
ほぼ完成しているようですし、移植しても良いのではないでしょうか。

**Comment by yumetodo** [comment]
了解です

``./utility/constant_range_loop.hpp``

とかですかね、置くとすると

**Comment by Nagarei** [comment]
それで良いと思います。

**Comment by Nagarei** [comment]
恐らくこちらもcloseで良いと思います。
