### ISSUE TITLE
p0267 : A Proposal to Add 2D Graphics Rendering and Display to C++への対応

### ISSUE THREAD

**Issue by yumetodo** [Nagarei/DxLibEx#72]
完全に見落としていたんですが、C++標準化委員会で2D描画を標準化しようという動きがあるみたいですね・・・。
http://www.open-std.org/JTC1/SC22/WG21/docs/papers/2016/p0267r1.pdf

class設計がmodifier/observerモデルというかgetter/setterモデルなのでJavaみたいで個人的には嫌なんですがそれはさておき、今後の設計であまりこれとかけ離れた設計にしないほうがいいのかなと思い、参考にするかどうかの決定と、参考にする場合の具体的な議論の場としてIssueを開きました。

**Comment by soukouki** [comment]
似せたらどんな利点があるんだろう。

**Comment by yumetodo** [comment]
![wg21-timeline](https://camo.githubusercontent.com/728db0e0faa9ec122b864f5c068459b236f5158a/68747470733a2f2f69736f6370702e6f72672f66696c65732f696d672f776732312d74696d656c696e652e706e67)
標準化委員会がC++2xに向け動いているということは、世の中に与える影響が大きいです。なんせ**標準**ですし。
全く同じにする必要は無いですが、あまりに違うと**標準**からずれた使いにくいものになってしまいます(標準=使いやすいとは限らないが(ex. std::chrono))

**Comment by soukouki** [comment]
http://www.open-std.org/JTC1/SC22/WG21/docs/papers/2016/p0267r1.pdf
は読み込みエラーで開けませんでした。
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0267r1.pdf
こちらでは開けました。
これ、出ちゃったらこのライブラリの必要性はどうなるんだろう。

**Comment by yumetodo** [comment]
コンパイル時処理とか他ライブラリ(OpenCV, FFmpeg)との連携しやすさとかかゆいところに手が届くとかそういう方向に・・・。
見た感じも一つ使いにくそうなので。

**Comment by yumetodo** [comment]
2D graphicの標準化はだいぶ前に頓挫した
