### ISSUE TITLE
Doxygenのドキュメントが古い気がする

### ISSUE THREAD

**Issue by soukouki** [Nagarei/DxLibEx#75]
3ヶ月前はちょっと古い気がします。
masterブランチにコミットやマージがあったら自動でアップするようにしたいです。

**Comment by yumetodo** [comment]
自動化は・・・。Travis-Clにgitとかいれてsshでpushすれば行けるんだろうけど、面倒なので・・・。
Linuxで動くようにinstall scriptとdoxygen compile scriptとデプロイscript書くとかめんd

後で更新しておきます

**Comment by soukouki** [comment]
そこまで変化をすぐに見たいものでもないですし、とりあえずは手動でいいかと。

**Comment by yumetodo** [comment]
更新しました
