### ISSUE TITLE
Clang with Microsoft CodeGen(7月):error : unknown type name 'IUnknown'

### ISSUE THREAD

**Issue by yumetodo** [Nagarei/DxLibEx#84]
# 問題

多分7月版からだけど

```
1>  In file included from C:\Program Files (x86)\Windows Kits\8.1\Include\um\windows.h:210:
1>  In file included from C:\Program Files (x86)\Windows Kits\8.1\Include\um\ole2.h:32:
1>  In file included from C:\Program Files (x86)\Windows Kits\8.1\Include\um\objbase.h:27:
1>C:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h(229,21): error : unknown type name 'IUnknown'
1>          static_cast<IUnknown*>(*pp);    // make sure everyone derives from IUnknown
```

のようなエラーが出るようになった。
# 解決策

`Windwos.h`をincludeしている箇所すべてを

``` cpp
#if !defined(CINTERFACE) && defined(__c2__) &&  __clang_major__ == 3 && __clang_minor__ == 8
//To avoid compile error
//C:\Program Files (x86)\Windows Kits\8.1\Include\um\combaseapi.h(229,21): error : unknown type name 'IUnknown'
//          static_cast<IUnknown*>(*pp);    // make sure everyone derives from IUnknown
#define CINTERFACE
#endif
#include <Windows.h>
```

のように置き換える

http://qiita.com/yumetodo/items/bd41f31f39dd590e8c80#windowsh%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6

**Comment by yumetodo** [comment]
DxLib.hをincludeしている部分も対応しないとですが、DxLibにバグレポ投げるのはやるとして、こっちでも対応するべきですかねぇ・・・

**Comment by Nagarei** [comment]
一応、DxLib.hの前にwindws.hをインクルードすることで、対応したほうが良いと思います。

**Comment by yumetodo** [comment]
あれ、手元ではDxLib.hを読み込んでいる部分は反応しない・・・おかしいな。
DxLib側で既に``CINTERFACE``をdefineしている・・・？んなばかな。

**Comment by yumetodo** [comment]
いや、``dxlibex.hpp``を読み込んでいたから、先の``tchar.hpp``への対策が効いてるだけみたいだ。やはりあとでバグレポ投げねば

**Comment by yumetodo** [comment]
http://dxlib.o.oo7.jp/cgi/patiobbs/patio.cgi

**Comment by yumetodo** [comment]
ところでこれはMSにバグレポを投げるべきなんだろうか・・・

**Comment by yumetodo** [comment]
そういやcommit messageにfixて書くと勝手に閉じるの忘れてた。

まあ治っているはず。問題があればreopenで

**Comment by yumetodo** [comment]
http://qiita.com/yumetodo/items/a8c408078766a5c81e31#comment-e1b90b86ed6ef274f86c

@egtra 氏より

```cpp
struct IUnknown;
#include <Windows.h>
```

で十分では？という指摘があった。

@Nagarei 
見た目のスッキリさの意味でこっちに書き換えます？

**Comment by Nagarei** [comment]
COM周りを使いたいというユースケースがあったので、書き換えしたいです。

**Comment by yumetodo** [comment]
@Nagarei 前方宣言してもエラーが消えるだけで使えるようにはならないと思うんですが・・・

**Comment by Nagarei** [comment]
詳しい検証はしていませんが、
```cpp
struct IUnknown;
#include <Windows.h>
#include "DxLib.h"
#include <dxlibex/graph2d.hpp>
#include <dxlibex/color.hpp>
#undef CINTERFACE
...
#include <Shlobj.h>
#pragma comment(lib, "Ole32.lib")
```
で`IShellFolder`(IUnknownを継承)を使うコードのコンパイルが通ったので、一部のものは前方宣言で使えそうです。

**Comment by Nagarei** [comment]
959警告くらい出ましたが、DxLibのコンパイル通りました。
各種コンパイルエラーを潰して、
DxCompileConfig.hの一番上に
```cpp
struct IUnknown;
#include <Unknwnbase.h>
```
って書きました。

**Comment by yumetodo** [comment]
本当だ。コンパイルが通る！
・・・一体どうやってだめなやつと通るやつを見分けろと・・・。

とりあえず書き換え確定ですかね

**Comment by yumetodo** [comment]
というわけで #96 投げました

**Comment by yumetodo** [comment]
>#include <Unknwnbase.h>がないと、IUnknownの定義がなくてエラーになります。

それは多分前に管理人さんにCINTERFACEをdefineするように修正をお願いしたからだと思うので
http://dxlib.o.oo7.jp/cgi/patiobbs/patio.cgi?mode=view&no=3882
reopenしてきました

**Comment by Nagarei** [comment]
エラーが直った原因はVisual Studio 2015 Update 3 Patch(KB3165756)ですかね...。
検証できるものでもないですが。

**Comment by yumetodo** [comment]
なるほど・・・。
